= URL Shortener

The code in this repo is from link:https://github.com/nelsontky[@nelsontky's] link:https://github.com/nelsontky/gh-pages-url-shortener[gh-pages-url-shortener].

The 404 page is a custom version of the page from link:https://github.com/itsron717[@itsron717's] link:https://github.com/itsron717/ParticleGround-Portfolio[Particle Portfolio Template].

The js code has been modified to use the issue.title as the shortener link and the issue.body as the destination.

== Adding Links (Guest)

If I've said you can add a link, make an issue with the title that you want as the end of the link url (e.g. '4a8ro0' -> billy.rip/gst/4a8ro0) and the body of the issue as the link you want to redirect to.

Issue titles should be unique and doing a quick search of issues with the same title will help you check this. A good way to make an id is using a random password generator set to numbers and alphabetical characters, with a length of around 6.

When adding links as a guest, they have to be approved before the link will work with the shortener, and the issue will be locked after approval.

The links will then end up under `gst` so billy.rip/gst/ID

== Adding Links (Enabled Users)

If I have enabled you as a user, you will be able to make links which are instantly available without them having to be checked and authorised first. You can choose a prefix for your urls, e.g. 'bb/'

Make an issue with the title that you want as the end of the link url (e.g. '4a8ro0' -> billy.rip/bb/4a8ro0) and the body of the issue as the link you want to redirect to.

Issue titles should be unique and doing a quick search of issues with the same title will help you check this. (It only needs to be unique within the titles you've created). A good way to make an id is using a random password generator set to numbers and alphabetical characters, with a length of around 6.

== ToDo

- [ ] Add pagination so more than 100 links are supported
- [ ] Add generate id page to create id that hasn't been used yet
